export const paintingData = [
  // Front Wall - Ethiopian Historical Art
  {
    imgSrc: `artworks/1.jpg`,
    width: 5,
    height: 3,
    position: { x: -15, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: "The Lion of Judah",
      artist: "Traditional Ethiopian Artist",
      description: "The Lion of Judah is a powerful symbol in Ethiopian culture, representing the Solomonic dynasty and the connection to King Solomon and the Queen of Sheba. This symbol appears on the Ethiopian flag and represents strength, courage, and divine authority.",
      historicalContext: "The Lion of Judah has been a central symbol in Ethiopian culture for over 3,000 years, representing the biblical connection between Ethiopia and Israel through the Queen of Sheba's visit to King Solomon.",
      significance: "This symbol represents Ethiopia's unique position as the only African country to maintain independence during the colonial era and its rich biblical heritage.",
      year: "Traditional Symbol",
      link: "#",
    },
  },
  {
    imgSrc: `artworks/2.jpg`,
    width: 5,
    height: 3,
    position: { x: -5, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: "Axum Obelisk",
      artist: "Ancient Axumite Civilization",
      description: "The Axum Obelisks are monumental stelae erected by the ancient Axumite civilization. These massive stone structures, some reaching 33 meters in height, were built to mark royal tombs and demonstrate the power and wealth of the Axumite kingdom.",
      historicalContext: "The Axumite Empire (100-940 CE) was one of the most powerful kingdoms in the ancient world, controlling trade routes between the Roman Empire and India. The obelisks date from the 3rd-4th centuries CE.",
      significance: "These obelisks represent the architectural and engineering achievements of ancient Ethiopia and the country's role in early global trade networks.",
      year: "3rd-4th century CE",
      link: "#",
    },
  },
  {
    imgSrc: `artworks/3.jpg`,
    width: 5,
    height: 3,
    position: { x: 5, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: "Ethiopian Orthodox Church Art",
      artist: "Ethiopian Orthodox Tradition",
      description: "Ethiopian Orthodox Church art is characterized by its distinctive style, vibrant colors, and religious iconography. These paintings often depict biblical scenes, saints, and angels in a unique Ethiopian interpretation.",
      historicalContext: "Ethiopian Orthodox Christianity dates back to the 4th century CE when King Ezana converted to Christianity. The art tradition has been preserved and developed over 1,600 years.",
      significance: "This art form represents the deep spiritual and cultural heritage of Ethiopia and its unique interpretation of Christianity.",
      year: "4th century CE - Present",
      link: "#",
    },
  },
  {
    imgSrc: `artworks/4.jpg`,
    width: 5,
    height: 3,
    position: { x: 15, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: "Harar City Walls",
      artist: "Harari People",
      description: "The ancient walled city of Harar is a UNESCO World Heritage site and one of the holiest cities in Islam. The city's distinctive architecture, with its narrow alleys and traditional houses, represents centuries of cultural exchange.",
      historicalContext: "Harar was founded in the 7th century and became a major center of Islamic learning and trade. The city walls were built in the 16th century to protect against Christian expansion.",
      significance: "Harar represents the rich Islamic heritage of Ethiopia and the country's role as a bridge between African and Middle Eastern cultures.",
      year: "7th-16th century",
      link: "#",
    },
  },
  
  // Back Wall - Ethiopian Cultural Heritage
  {
    imgSrc: `artworks/5.jpg`,
    width: 5,
    height: 3,
    position: { x: -15, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: "Ethiopian Coffee Ceremony",
      artist: "Ethiopian Cultural Tradition",
      description: "The Ethiopian coffee ceremony is a central part of Ethiopian culture and hospitality. This elaborate ritual involves roasting green coffee beans, grinding them, and brewing coffee in a traditional clay pot called a jebena.",
      historicalContext: "Coffee was first discovered in Ethiopia by a goat herder named Kaldi in the 9th century. The coffee ceremony has been practiced for over 1,000 years and remains a vital social custom.",
      significance: "This ceremony represents Ethiopia's status as the birthplace of coffee and the importance of hospitality and community in Ethiopian culture.",
      year: "9th century - Present",
      link: "#",
    },
  },
  {
    imgSrc: `artworks/6.jpg`,
    width: 5,
    height: 3,
    position: { x: -5, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: "Ethiopian Traditional Dress",
      artist: "Ethiopian Weavers",
      description: "Ethiopian traditional dress, particularly the habesha kemis (white dress) and netela (shawl), represents the country's rich textile traditions. These garments are made from hand-woven cotton and feature intricate embroidery.",
      historicalContext: "Ethiopian textile traditions date back thousands of years, with evidence of cotton cultivation and weaving found in archaeological sites. The white dress tradition is associated with purity and religious significance.",
      significance: "Traditional dress represents Ethiopian identity, cultural pride, and the country's unique fashion heritage.",
      year: "Ancient - Present",
      link: "#",
    },
  },
  {
    imgSrc: `artworks/7.jpg`,
    width: 5,
    height: 3,
    position: { x: 5, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: "Ethiopian Highlands",
      artist: "Nature",
      description: "The Ethiopian Highlands are a rugged mountain range that covers much of Ethiopia. These highlands are home to unique ecosystems, including the Ethiopian wolf and gelada baboon, and are crucial for the country's agriculture.",
      historicalContext: "The highlands have been inhabited for millions of years, with early hominins like Lucy (Australopithecus afarensis) living in this region. The highlands have protected Ethiopia from external invasions throughout history.",
      significance: "The highlands represent Ethiopia's natural heritage and have played a crucial role in the country's history, culture, and biodiversity.",
      year: "Geological Time",
      link: "#",
    },
  },
  {
    imgSrc: `artworks/8.jpg`,
    width: 5,
    height: 3,
    position: { x: 15, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: "Ethiopian Music and Dance",
      artist: "Ethiopian Musicians",
      description: "Ethiopian music and dance are characterized by their unique rhythms, instruments like the masinko (fiddle) and krar (lyre), and traditional dance forms. These cultural expressions are central to Ethiopian identity.",
      historicalContext: "Ethiopian music traditions date back thousands of years, with influences from ancient Egypt, the Middle East, and indigenous African cultures. The music has evolved while maintaining its distinctive character.",
      significance: "Ethiopian music and dance represent the country's rich cultural diversity and serve as a means of storytelling and community bonding.",
      year: "Ancient - Present",
      link: "#",
    },
  },
  
  // Left Wall - Ethiopian Wildlife and Nature
  {
    imgSrc: `artworks/9.jpg`,
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: -15 },
    rotationY: Math.PI / 2,
    info: {
      title: "Ethiopian Wolf",
      artist: "Wildlife Photography",
      description: "The Ethiopian wolf is the rarest canid in the world and is found only in the Ethiopian Highlands. This endangered species is adapted to life in the high-altitude grasslands and plays a crucial role in the ecosystem.",
      historicalContext: "The Ethiopian wolf has been present in the highlands for thousands of years and is considered a national treasure. Conservation efforts are ongoing to protect this unique species.",
      significance: "The Ethiopian wolf represents Ethiopia's unique biodiversity and the importance of conservation efforts to protect endangered species.",
      year: "Endemic Species",
      link: "#",
    },
  },
  {
    imgSrc: `artworks/10.jpg`,
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: -5 },
    rotationY: Math.PI / 2,
    info: {
      title: "Gelada Baboon",
      artist: "Wildlife Photography",
      description: "The gelada baboon is a unique primate found only in the Ethiopian Highlands. These social animals live in large groups and are known for their distinctive red chest patches and complex social behaviors.",
      historicalContext: "Geladas have been present in the Ethiopian Highlands for millions of years and have adapted to the harsh high-altitude environment. They are often seen in close proximity to human settlements.",
      significance: "Geladas represent Ethiopia's unique wildlife and the country's role in primate evolution and biodiversity conservation.",
      year: "Endemic Species",
      link: "#",
    },
  },
  {
    imgSrc: `artworks/11.jpg`,
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: 5 },
    rotationY: Math.PI / 2,
    info: {
      title: "Ethiopian Highlands Flora",
      artist: "Nature",
      description: "The Ethiopian Highlands are home to unique plant species, including the giant lobelia and various endemic flowers. These high-altitude ecosystems are crucial for biodiversity and water resources.",
      historicalContext: "The highland flora has evolved over millions of years in isolation, creating unique ecosystems found nowhere else in the world. These plants are adapted to the harsh high-altitude conditions.",
      significance: "The highland flora represents Ethiopia's unique biodiversity and the importance of protecting these fragile ecosystems.",
      year: "Geological Time",
      link: "#",
    },
  },
  {
    imgSrc: `artworks/12.jpg`,
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: 15 },
    rotationY: Math.PI / 2,
    info: {
      title: "Blue Nile Falls",
      artist: "Nature",
      description: "The Blue Nile Falls, known locally as 'Tis Abay' (smoking water), is one of Ethiopia's most spectacular natural wonders. The falls are located on the Blue Nile River and are a major tourist attraction.",
      historicalContext: "The Blue Nile has been a crucial water source for Ethiopia and downstream countries for thousands of years. The falls have been referenced in Ethiopian literature and folklore.",
      significance: "The Blue Nile Falls represents Ethiopia's natural beauty and the country's role as the 'Water Tower of Africa'.",
      year: "Natural Formation",
      link: "#",
    },
  },
  
  // Right Wall - Ethiopian Architecture and Monuments
  {
    imgSrc: `artworks/13.jpg`,
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: -15 },
    rotationY: -Math.PI / 2,
    info: {
      title: "Fasil Ghebbi Palace",
      artist: "Gondarine Architecture",
      description: "Fasil Ghebbi is a fortress-city in Gondar that served as the residence of Ethiopian emperors from the 17th to 19th centuries. The complex includes palaces, churches, and other buildings in a unique architectural style.",
      historicalContext: "Gondar was established as the capital of Ethiopia in 1636 by Emperor Fasilides. The city became a center of Ethiopian culture and architecture, known as the 'Camelot of Africa'.",
      significance: "Fasil Ghebbi represents Ethiopia's imperial history and the country's unique architectural heritage, combining local and foreign influences.",
      year: "17th-19th century",
      link: "#",
    },
  },
  {
    imgSrc: `artworks/14.jpg`,
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: -5 },
    rotationY: -Math.PI / 2,
    info: {
      title: "Debre Berhan Selassie Church",
      artist: "Ethiopian Orthodox Architecture",
      description: "Debre Berhan Selassie Church in Gondar is famous for its ceiling paintings of angels. The church is considered one of the most beautiful examples of Ethiopian Orthodox church architecture and art.",
      historicalContext: "The church was built in the 17th century during the reign of Emperor Iyasu I. It survived the destruction of Gondar by Sudanese invaders in the 1880s, reportedly protected by a swarm of bees.",
      significance: "This church represents the artistic and architectural achievements of the Gondarine period and the deep religious faith of the Ethiopian people.",
      year: "17th century",
      link: "#",
    },
  },
  {
    imgSrc: `artworks/15.jpg`,
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: 5 },
    rotationY: -Math.PI / 2,
    info: {
      title: "Ethiopian Traditional Houses",
      artist: "Ethiopian Architecture",
      description: "Traditional Ethiopian houses vary by region but often feature distinctive round or rectangular designs, thatched roofs, and mud or stone construction. These houses are adapted to local climates and materials.",
      historicalContext: "Traditional house designs have evolved over thousands of years, reflecting local environmental conditions, available materials, and cultural preferences. These designs continue to influence modern Ethiopian architecture.",
      significance: "Traditional houses represent Ethiopia's architectural diversity and the ingenuity of local builders in creating sustainable, climate-appropriate dwellings.",
      year: "Traditional - Present",
      link: "#",
    },
  },
  {
    imgSrc: `artworks/16.jpg`,
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: 15 },
    rotationY: -Math.PI / 2,
    info: {
      title: "Ethiopian Market Scene",
      artist: "Ethiopian Daily Life",
      description: "Ethiopian markets are vibrant centers of commerce and social interaction. These markets feature colorful displays of spices, textiles, food, and crafts, representing the country's rich trading traditions.",
      historicalContext: "Ethiopia has been a center of trade for thousands of years, with markets serving as crucial nodes in ancient trade networks connecting Africa, the Middle East, and Asia.",
      significance: "Ethiopian markets represent the country's commercial heritage, cultural diversity, and the importance of community and social interaction in Ethiopian life.",
      year: "Ancient - Present",
      link: "#",
    },
  },
];
